FROM docker.io/oven/bun:1.1-alpine AS builder

WORKDIR /app

COPY ui/package.json ui/bun.lockb* ./
RUN bun install --frozen-lockfile

COPY ui/ ./
RUN bunx --bun vite build

FROM docker.io/library/nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
